### ISSUE TITLE
Error on signup page

### ISSUE THREAD

**Issue by Scsharath2** [aws-samples/aws-serverless-workshops#101]
Hi,

I'm getting error on signup page "There is no user pool configured in /js/config.js. You'll configure this in Module 2 of the workshop" even after making changes(Module 2) in /js/config.js .
Strange thing is the changes are reflected in bucket /js/config.js file but on signup page i see error.

**Comment by Scsharath2** [comment]
Never Mind :) 
I fixed it

**Comment by jayboy-mabushi** [comment]
how did you fix it?

**Comment by dumbcoder2399** [comment]
I am having the same problem. how to fix it?
