### ISSUE TITLE
DevOps Module 2 returns an empty array

### ISSUE THREAD

**Issue by zhulika** [aws-samples/aws-serverless-workshops#102]
I finished module 1 last night, without problems. I started Module 2 up to, but not including the "test" phase.

This morning, when I try the test phase, I get no unicorns. The table is empty, even though I have "updated" it to include Shadowfox (with a 200 status). Looking at the table (it's the only table on my account), the storage capacity is zero. There were no errors AFAICS, so this seems to be broken

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
