### ISSUE TITLE
Role for ListUnicornRides doesn't include Scan for DynamoDB

### ISSUE THREAD

**Issue by NanoMarc** [aws-samples/aws-serverless-workshops#105]
The role for the function ListUnicornRides which is WildRydesLambda should allow Scan on DynamoDB. By default, it only allows PutItem.

**Comment by mikedeck** [comment]
This is intentional. The requestRide function only uses the PutItem action. The role provides a least privilege policy for that function.

**Comment by gjmveloso** [comment]
Customers that doesn't want to use the provided `prerequisites.yaml at 5_OAuth from WebApplication module may want to be advised to change `WildRydesLambda` IAM Role to allow `ddb:Scan`

WIP at #229
