### ISSUE TITLE
DevOps Module 4 IAM Policy Change KO in visual editor

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/aws-serverless-workshops#118]
https://github.com/aws-samples/aws-serverless-workshops/tree/master/DevOps/4_MultipleEnvironments#user-content-1c-update-codestarworkercodepipelinerolepolicy-iam-policy

1c. Update CodeStarWorkerCodePipelineRolePolicy IAM Policy
Step 2 : Update the allowed CloudFormation Resource pattern 

```
Before: arn:aws:cloudformation:{region}:{accountId}:stack/awscodestar-uni-api-lambda/*

After: arn:aws:cloudformation:{region}:{accountId}:stack/awscodestar-uni-api-lambda*
```
This change does not work in the visual editor

![image](https://user-images.githubusercontent.com/308444/41499876-ac1f8912-7188-11e8-821d-c3d0901d8e5b.png)

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
