### ISSUE TITLE
No error document

### ISSUE THREAD

**Issue by marcgott** [aws-samples/aws-serverless-workshops#119]
add error.html for S3 website

**Comment by mikedeck** [comment]
One of our goals is to keep the workshop as simple as possible while still demonstrating the salient features of the platform. In this case, adding the extra step to the instructions to configure an error document, while minimal, doesn't really add anything meaningful to the scope of what we're teaching students. I think leaving the error document configuration out is the simpler way to configure things, but it's still obvious to anyone doing the workshop that you could specify an error document if you wanted.
