### ISSUE TITLE
DevOps Module 1 - Create seed doesn't account for us-east-2

### ISSUE THREAD

**Issue by kogden** [aws-samples/aws-serverless-workshops#129]
The doc says it will be configured for you just fine, but clicking on us-east will only generate the seed file for us-east-1. There is no option for us-east-2. 

I do not know how to get past this step.

**Comment by mikedeck** [comment]
us-east-2 is not currently a supported region for this workshop. We will update to add support shortly. In the meantime, can you run in a different region?

**Comment by mikedeck** [comment]
@samdengler We should make sure the base CloudFormation template that drives the code commit repo seeding is part of this repo, I don't see it here. We should also move the templates to the main `wildrydes-[REGION]` buckets. Let me know if you need help setting that up.

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
