### ISSUE TITLE
Module 3 : XRAY code not well explained

### ISSUE THREAD

**Issue by gmarchand** [aws-samples/aws-serverless-workshops#139]
The lab explains how to solve the [performance issue](https://github.com/aws-samples/aws-serverless-workshops/tree/master/DevOps/3_XRay#1-fix-code-bug-1), but it does not explain how to implement XRAY code 

https://github.com/aws-samples/aws-serverless-workshops/tree/master/DevOps/3_XRay#1-fix-code-bug-1

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
