### ISSUE TITLE
X-Ray Module 3: error info missing

### ISSUE THREAD

**Issue by gbarker** [aws-samples/aws-serverless-workshops#142]
I get an empty `Exceptions` tab on the X-Ray pop up `Subsegment - List Unicorns` when following the tutorial. 

Work around: deploy with the simulated error active `err = Error("something is wrong");`  and the simulated delay commented out `// const isDelayed = true;`

It appears the the delay is some how interfering with the error/stacktrace capture.

**Comment by samdengler** [comment]
Thanks for your feedback.  We've update the DevOps Serverless Workshop with new content: https://cicd.serverlessworkshops.io/
