### ISSUE TITLE
Image Processing CloudFormation template - NodeJS 4.3 EOL

### ISSUE THREAD

**Issue by xlo2** [aws-samples/aws-serverless-workshops#177]
In the Image Processing module, the CloudFormation template uses NodeJS 4.3 runtime for the deployment of the lambdas. This version is EOL and the stack deployment fails.
Replacing NodeJS 4.3 with NodeJS 6.10 fixes the problem.

**Comment by angelarw** [comment]
Thanks for reporting the problem. The templates are now fixed with the updated nodejs runtime.
