### ISSUE TITLE
ImageProcessing module fails cloudformation stack execution

### ISSUE THREAD

**Issue by jkuhnert** [aws-samples/aws-serverless-workshops#179]
https://github.com/aws-samples/aws-serverless-workshops/tree/master/ImageProcessing#2-deploy-amazon-s3-aws-lambda-and-amazon-dynamodb-resources-using-aws-cloudformation

It rolls back automatically after it runs into an error about nodejs 4.something not being available anymore.

**Comment by tbulding** [comment]
I got the same error, I modified the template locally to use nodejs8.10 and it completed successfully.

**Comment by angelarw** [comment]
Thanks for reporting the problem. The templates have been updated on the hosting bucket.
