### ISSUE TITLE
PutJobSuccessResult Permission

### ISSUE THREAD

**Issue by rj175** [aws-samples/aws-serverless-workshops#224]
Hello,

I am currently working through the DevOps course, I'm right at the end of the multiple environment section however when running the pipleline after adding the beta step I am getting the following error:
```
Action execution failed
The AWS Lambda function uni-api-test-setup failed to return a result. Check the function to verify that it has permission to call the PutJobSuccessResult action and that it made a call to PutJobSuccessResult.
```
This is happening at the beta InvokeLambdaTestFunction step.

Any help would be great.

**Comment by samdengler** [comment]
@rj175 - the multi-environment module is not currently working due to a breaking change in CodeStar permission management.  It is not included in the navigation of modules, but the code is still in the repo.  I'll add a note in the module to make that clearer.

**Comment by rj175** [comment]
@samdengler Thanks! I was starting to think I was loosing my mind! Please feel free to close this issue

**Comment by samdengler** [comment]
@rj175 Apologies for the mental distress!  I'll close the issue, but plan to update the module this week with the additional warning.  Thanks for the feedback!
