### ISSUE TITLE
Image Processing Module - CFN fail - nodejs8.10 runtime has been deprecated

### ISSUE THREAD

**Issue by samAnnisBrown** [aws-samples/aws-serverless-workshops#270]
CFN fails to deploy due to deprecation of nodejs8.10 runtime.  Needs update to 10.x or 12.x (I was running this ap-southeast-2)

**Comment by SamualBrown** [comment]
After having gone through the `Image Processing` module in its entirety, I've found that all the Lambdas work on Node12.x except `wildrydes-step-module-resources-ThumbnailFunction`.  This function fails with both Node10.x and 12.x, so will likely require a slight rewrite.

Other than that, a find/replace in the CFN moving from 8.10 to 12.x should be sufficient.

**Comment by samdengler** [comment]
Thanks for your feedback.  We have fixed the ImageMagick issue and deployed a new version of the workshop here: https://image-processing.serverlessworkshops.io/
