### ISSUE TITLE
Image Processing lab: Invalid SNS resource in Step Functions declaration and other minor issues

### ISSUE THREAD

**Issue by deki** [aws-samples/aws-serverless-workshops#297]
- https://image-processing.serverlessworkshops.io/extra-credit/native-integrations.html “Resource”: “arnstates::publish” is invalid, should be “arn:aws:states:::sns:publish”
- https://image-processing.serverlessworkshops.io/implementation/metadata-persistence.html step 5, image reference https://image-processing.serverlessworkshops.io/images/6-update-state-machine-persistence-2.png is broken
- https://image-processing.serverlessworkshops.io/implementation/state-machine.html fix typo step 11 Create State Macine

Can you please point me where the sources have been moved to? I'm willing to submit a PR for that.

**Comment by bugmang** [comment]
I believe these issues were addressed in the August 2021 rewrite. Closing as these are no longer valid links.
