### ISSUE TITLE
few updates needed - picked up during AWS re/Start Immerion Day deliver 28 January

### ISSUE THREAD

**Issue by KFill21** [aws-samples/aws-serverless-workshops#302]
This was shared by mjhume@ who delivered this workshops for re/Start alongside julbeck@ mmlm@

Section: 1 Static Web Hosting

Repository
Create the git repository
Step 4. Split out the WildRydesVue code into its own branch: 
If this step fails, and you then run sudo yum install git-subtree 

If this happens, the user needs to be told to re-run step 4 above
BEFORE going to step 5 Create a new directory for your CodeCommit repo: 

This caused real problems for nearly everyone last week

Modify
1.From your Cloud9 environment open the index.html file in the /wild-rydes/public/ directory of the repository. - should be /WildRydesVue/public/

2 User Management
Amplify CLI
3.Go to the root wild-rydes directory of the repository: - should be WildRydesVue

App Client 
5.You will see that a new App client has been generated. Your web application is configured to use this App client via a config file located in wildrydes/src/aws-exports.js. - should be WildRydesVue/src/aws-exports.js.

3. Deploy the site with the AWS Amplify Console
2.Underneath Deploy choose Get Started
            Step missing - now requires Host your web app - Get Started
3.Select AWS CodeCommit and choose Continue

P.S watch for when they create a dynamodb table, they need to ensure they spell the table name and partition key exactly as advised, if not API GW / Lambda will respond with errors

Rides for the Table name 
RideId for the Partition key

**Comment by humem001** [comment]
Please ignore the P.S note at the bottom of the previous comment, this is not an issue. This was just a heads up for the next team who ran this workshop.

**Comment by rts-rob** [comment]
This workshop lives in https://github.com/aws-samples/aws-serverless-webapp-workshop - please review that repository and if any issues remain unaddressed, file an issue there.

Thank you for the submission!
