### ISSUE TITLE
image processing workshop lambda needs to be updated to Python3

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/aws-serverless-workshops#313]
https://www.image-processing.serverlessworkshops.io/03_implementation/20_cloudformation.html currently fails with error 
CopyS3ObjectsFunction
CREATE_FAILED
Resource handler returned message: "The runtime parameter of python2.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 85b34252-907e-4d73-bf81-6ee1ab1ec836, Extended Request ID: null)" (RequestToken: 9610523c-f836-6305-6278-2ed86ee2538c, HandlerErrorCode: InvalidRequest)

**Comment by bugmang** [comment]
This was changed to Python3.6 (and node 14 for that runtime) early 2022

**Comment by bugmang** [comment]
Further updated to 3.9 here: https://github.com/aws-samples/aws-serverless-workshops/pull/331
