### ISSUE TITLE
ImageProcessing CloudFormation stack fails: deprecated python3.6 runtime

### ISSUE THREAD

**Issue by marcijef** [aws-samples/aws-serverless-workshops#330]
The ImageProcessing workshop CloudFormation template creates a Lambda Function resource with the deprecated Python3.6 runtime.  https://github.com/aws-samples/aws-serverless-workshops/blob/e58f888a6f3d464109c5702e55122c817b74d3f5/ImageProcessing/src/cloudformation/module-setup.yaml#L234

**Comment by bugmang** [comment]
This was updated via merge here:
https://github.com/aws-samples/aws-serverless-workshops/pull/331
