### ISSUE TITLE
S3 WebSite Endpoint incorrect for US-EAST-1

### ISSUE THREAD

**Issue by georgmao** [aws-samples/aws-serverless-workshops#37]
For the Web Application (WildRydes):

#In module 1, Under Architecture, the listed endpoint is incorrect for US-EAST-1:
 http://{your-bucket-name}.s3-website.{region}.amazonaws.com

It should be a - (dash) in between s3-website and {region}

**Comment by ScottBrenner** [comment]
Open a pull request for this, should be a simple fix.
