### ISSUE TITLE
Web security vulnerability- WebApplication's configure.js's  cognito pool information exposed to the public

### ISSUE THREAD

**Issue by mingqin1** [aws-samples/aws-serverless-workshops#43]
Hi:
  Thanks for releasing this tutorial about serverless web application. I am big fun of AWS serverless stack.

   I noticed the  attributes such as cognito user pool id , pool client id and region are exposed to public through configure.js.  This is could be very serious web security issue.   Those information should be hidden into lamba code side. The user registration, verification and login , this tutorial is built on client javascript's talking with cognito directly, which might not be the best design.  Those events should be migrated to Lambda side.

![capture](https://user-images.githubusercontent.com/6629272/30244504-b79db2d8-9573-11e7-8104-b63659cd7528.JPG)

**Comment by shazic** [comment]
@mingqin1 - do you know any tutorial on how to do this?

**Comment by mikedeck** [comment]
This is not a vulnerability. The Cognito user pool ID and client ID are intended to be configured this way. Cognito User Pools is designed to be accessed directly from the browser or other client application. You can add your own API in front of the Cognito endpoint if you would like to hide the fact that you are using Cognito, but this should not be done just for security concerns.

**Comment by Brainsway-Cloud** [comment]
Without a secret key to limit access, can I limit who can add a user to the pool and who can set attributes?
