### ISSUE TITLE
WildRydes maps crashed in OSX Sierra

### ISSUE THREAD

**Issue by kktam** [aws-samples/aws-serverless-workshops#49]
This is a bug report on WebApplication, 4_RESTfulAPIs section.

In Section [4_RESTfulAPIs](https://github.com/awslabs/aws-serverless-workshops/tree/master/WebApplication/4_RESTfulAPIs) of the WebApplication workshop the final application crashes when the users loads the ride.html page after a success authentication.

In the last step of Secton 4_RESTfulAPIs :

```
Implementation Validation

Visit /ride.html under your website domain.
```

When the page renders in a Mac installation, the page crashed and as the result, the map and users data are not displayed on the right side of the control widget. (see attached images)

When I open the debugger there is a javascript exception and as follows:

```
init.js:1797 Uncaught TypeError: Cannot read property 'getParameter' of null
    at new a (init.js:1797)
    at l.attach (MapView.js:305)
    at c.e.attachChild (MapView.js:294)
    at c.k.attachChildren (MapView.js:301)
    at c.k.render (MapView.js:297)
    at c.e.render (MapView.js:293)
    at c.renderFrame (MapView.js:292)
    at Object.render (MapView.js:290)
    at h._animationFrame (init.js:332)
```

Here are some screenshots of the crash:

[Website screenshot at time of crash](https://s3-us-west-2.amazonaws.com/kt-images/WildRydes/CapturFiles-20170915_111645.png)

[Stack trace](https://s3-us-west-2.amazonaws.com/kt-images/WildRydes/CapturFiles-20170915_111800.png)

[Chrome version file](https://s3-us-west-2.amazonaws.com/kt-images/WildRydes/chrome-version.txt)

Here is some hardware information

MacBook Pro
Processor 2.3 GHz Intel Core i5
Memory 8 GB 1333 MHz DDR3
Graphics Intel HD Graphics 3000 512 MB

Software

OSX Sierra version 10.12.6

Browser

Google Chrome 60.0.3112.113 (attached version text file)

**Comment by mikedeck** [comment]
Sorry this issue has lingered for so long. Unfortunately I cannot reproduce this. If the issue persists please reopen.
