### ISSUE TITLE
No Unicorn Icon?

### ISSUE THREAD

**Issue by Intelrunner** [aws-samples/aws-serverless-workshops#56]
So, everything seems to work fine, but I can't get a unicorn icon to fly to my location for pickup...

**Comment by shazic** [comment]
I got the same issue when I had tried this a couple of months back. There was no unicorn icon flying to the pickup point. 

Is there anyone who has faced this issue and was able to identify what went wrong?

**Comment by matthts** [comment]
Just went through the complete workshop. Everything seems fine except for the unicorn showing up. Cleared cache, separate browsers, the normal stuff.. No unicorns!

**Comment by matthts** [comment]
Went through the API gateway. Seems I forgot to check the proxy integration on the Post method.
(i. Check the box for Use Lambda Proxy integration.)
Deleted the API and recreated (setting the proxy checkbox did not fix it). It now works.

If you ran into the same issue then you have this in the CloudWatch log: TypeError: Cannot read property 'authorizer' of undefined at exports.handler (/var/task/index.js:26:30).

**Comment by TurnipEntropy** [comment]
You do not need to delete the API and recreate it. You have access to those options in the Integration Request box:

Go to resources, cliikc on the POST method, it will take you to the Method Execution screen. Then click on the Integration Request box and check the Use Lambda Proxy Integration.

**Comment by Fountain** [comment]
I had to make the following changes for assets to load properly:
```
<!-- ride.html -->
- <link rel="stylesheet" href="/css/ride.css">
- <link rel="stylesheet" href="/css/message.css">
+ <link rel="stylesheet" href="css/ride.css">
+ <link rel="stylesheet" href="css/message.css">
```
and
```
// esri-map.js
- url: '/images/unicorn-icon.png',
+ url: 'images/unicorn-icon.png',
```

**Comment by mikedeck** [comment]
It looks like this can be caused either by a misconfiguration of your API as well as if you are using the path-style URLs for S3 (i.e. http://s3.amazonaws.com/bucket) instead of the website endpoint. The latter was an issue because of a problem with absolute URL references assuming ride.html was being served from the root of the domain. I've updated the website content to avoid absolute path references so this should not be an issue anymore.
