### ISSUE TITLE
Better feedback please

### ISSUE THREAD

**Issue by yoshgoodman** [aws-samples/aws-serverless-workshops#79]
Invalid HTTP methods in SAM template are not reported in error messages.

Build should break

**Comment by mikedeck** [comment]
You should see an error in the stack events when deploying a template with an invalid HTTP method. If you'd like to request a different behavior or additional validation, please raise an issue in the https://github.com/awslabs/serverless-application-model repository. This is not the right repo to use for feature requests for SAM or any AWS services.
