### ISSUE TITLE
Document map processing in Data Processing workshop

### ISSUE THREAD

**Issue by matsev** [aws-samples/aws-serverless-workshops#81]
Please provide instructions, hints or suggestions of how to plot latitude and longitude on a map in the [Data Processing](https://github.com/awslabs/aws-serverless-workshops/tree/master/DataProcessing) workshop.

In the [Extra Credit](https://github.com/awslabs/aws-serverless-workshops/tree/master/DataProcessing/5_DataArchiving#extra-credit) section of the "Module 5: Data Archiving" instructions of the DataProcessing workshop it is stated _(emphasis mine)_:

> Write a query for the latitude and longitude point pairs a unicorn traveled on a trip _and plot them on a map to see the unicorn's path_. 

The Athena query creation is pretty straight forward (basically modify the provided query), but there is nothing in this lab that suggest how the result can be plotted on a map.

**Comment by mikedeck** [comment]
This comment is very much intended to be an exercise for the reader. To do this, you would need to use a 3rd party tool or library to build a map with this data overlaid.

I'll update the instructions to remove that part of the suggestion.
